// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blogdatalayer.dbcontext;

#nullable disable

namespace blogdatalayer.Migrations
{
    [DbContext(typeof(appdbcontext))]
    [Migration("20260217111619_addreply")]
    partial class addreply
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("blogdatalayer.entities.comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<int>("postid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("postid");

                    b.HasIndex("userid");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("blogdatalayer.entities.commentlike", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("commentid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("commentid");

                    b.HasIndex("userid");

                    b.ToTable("commentlikes", (string)null);
                });

            modelBuilder.Entity("blogdatalayer.entities.like", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<int>("postid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("postid");

                    b.HasIndex("userid");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("blogdatalayer.entities.post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("authorid")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ispublished")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.HasIndex("authorid");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("blogdatalayer.entities.reply", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("commentid")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("commentid");

                    b.HasIndex("userid");

                    b.ToTable("replies", (string)null);
                });

            modelBuilder.Entity("blogdatalayer.entities.replylike", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("replyid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("replyid");

                    b.HasIndex("userid");

                    b.ToTable("replylikes", (string)null);
                });

            modelBuilder.Entity("blogdatalayer.entities.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("blogdatalayer.entities.comment", b =>
                {
                    b.HasOne("blogdatalayer.entities.post", "post")
                        .WithMany("comments")
                        .HasForeignKey("postid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blogdatalayer.entities.user", "user")
                        .WithMany("comments")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("blogdatalayer.entities.commentlike", b =>
                {
                    b.HasOne("blogdatalayer.entities.comment", "comment")
                        .WithMany("commentlikes")
                        .HasForeignKey("commentid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blogdatalayer.entities.user", "user")
                        .WithMany("commentlikes")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("comment");

                    b.Navigation("user");
                });

            modelBuilder.Entity("blogdatalayer.entities.like", b =>
                {
                    b.HasOne("blogdatalayer.entities.post", "post")
                        .WithMany("likes")
                        .HasForeignKey("postid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blogdatalayer.entities.user", "user")
                        .WithMany("likes")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("blogdatalayer.entities.post", b =>
                {
                    b.HasOne("blogdatalayer.entities.user", "author")
                        .WithMany("posts")
                        .HasForeignKey("authorid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("author");
                });

            modelBuilder.Entity("blogdatalayer.entities.reply", b =>
                {
                    b.HasOne("blogdatalayer.entities.comment", "comment")
                        .WithMany("replies")
                        .HasForeignKey("commentid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blogdatalayer.entities.user", "user")
                        .WithMany("replies")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("comment");

                    b.Navigation("user");
                });

            modelBuilder.Entity("blogdatalayer.entities.replylike", b =>
                {
                    b.HasOne("blogdatalayer.entities.reply", "reply")
                        .WithMany("replylikes")
                        .HasForeignKey("replyid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blogdatalayer.entities.user", "user")
                        .WithMany("replylikes")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("reply");

                    b.Navigation("user");
                });

            modelBuilder.Entity("blogdatalayer.entities.comment", b =>
                {
                    b.Navigation("commentlikes");

                    b.Navigation("replies");
                });

            modelBuilder.Entity("blogdatalayer.entities.post", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("likes");
                });

            modelBuilder.Entity("blogdatalayer.entities.reply", b =>
                {
                    b.Navigation("replylikes");
                });

            modelBuilder.Entity("blogdatalayer.entities.user", b =>
                {
                    b.Navigation("commentlikes");

                    b.Navigation("comments");

                    b.Navigation("likes");

                    b.Navigation("posts");

                    b.Navigation("replies");

                    b.Navigation("replylikes");
                });
#pragma warning restore 612, 618
        }
    }
}
